#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <template_icons.h>

int32_t template_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm template!");

    return 0;
}
